import React, { useState, useRef } from 'react';

import soundlogVideo from "../assets/videos/SoundlogVideo.mov";
import pacmanVideo from "../assets/videos/PacmanVideo.mov";
import bplustreeImage from "../assets/images/BPlusTree.png";
import miniblogVideo from "../assets/videos/MiniBlogVideo.mov";
import minimovielog from "../assets/videos/MiniMovieLogVideo.mov";

const projectsData = [
  {
    id: 1,
    title: 'Soundlog',
    mediaType: 'video',
    mediaUrl: soundlogVideo,
    description: 'AI-powered social music journaling platform. Integrates DistilRoBERTa emotion classification with Spotify recommendations — reduced p95 latency from 4.7s to 0.22s via Redis caching and Celery pre-warming. Daily prompts generated by Gemini API. Deployed on AWS EC2/S3 with Nginx and Gunicorn.',
    detailsLink: '#',
    githubLink: 'https://github.com/sok610/soundlog',
  },
  {
    id: 2,
    title: 'Cactus',
    mediaType: 'video',
    mediaUrl: pacmanVideo,
    description: 'Real-time IoT environmental monitoring system. ESP32 microcontrollers stream temperature, humidity, and soil moisture via MQTT to a full cloud pipeline: Kafka → InfluxDB → live Grafana dashboards with alerting. All components containerized with Docker on AWS EC2.',
    detailsLink: '#',
    githubLink: 'https://github.com/sok610/cactus-monitor',
  },
  {
    id: 3,
    title: 'PoliticianInfo',
    mediaType: 'image',
    mediaUrl: bplustreeImage,
    description: 'SaaS platform serving comprehensive data on 500+ politicians by state. Built with Ruby on Rails, Google Maps API, Google Civic API, and Google News API. Achieved 60% test coverage with RSpec, Cucumber, and Capybara.',
    detailsLink: '#',
    githubLink: '#',
  },
  {
    id: 4,
    title: 'Mini Blog',
    mediaType: 'video',
    mediaUrl: miniblogVideo,
    description: 'A minimalist blogging platform built with Django and Tailwind CSS.',
    detailsLink: '#',
    githubLink: 'https://github.com/sok610/mini-blog',
  },
  {
    id: 5,
    title: 'Mini Movie Log',
    mediaType: 'video',
    mediaUrl: minimovielog,
    description: 'Full-stack movie journaling app built with Node.js, Express.js, MongoDB, and Tailwind CSS. Users can write, edit, and search movie reviews with star ratings and a responsive UI.',
    detailsLink: '#',
    githubLink: 'https://github.com/sok610/minimovielog',
  },
];


function ProjectsPage() {
  const [activeProjectId, setActiveProjectId] = useState(1);
  const activeProject = projectsData.find(p => p.id === activeProjectId);

  const videoRef = useRef(null);
  const [isPlaying, setIsPlaying] = useState(false);

  const handleVideoControl = () => {
    if (isPlaying) {
      videoRef.current.pause();
    } else {
      videoRef.current.play();
    }
    setIsPlaying(!isPlaying); // 재생 상태를 반전시킴
  };
  // --- 여기까지 추가 ---

  return (
    <div className="page-content project-tab-view">
      <div className="project-tabs">
        {projectsData.map((project) => (
          <button
            key={project.id}
            className={`tab-button ${project.id === activeProjectId ? 'active' : ''}`}
            onClick={() => {
              setActiveProjectId(project.id);
              setIsPlaying(false);
            }}
          >
            {project.id === activeProjectId ? '•' : project.id}
          </button>
        ))}
      </div>

      <div className="project-content">
        {activeProject && (
          <div className="project-item">
            <div className="project-media">
              {activeProject.mediaType === 'video' ? (
                <>
                  <video 
                    ref={videoRef}
                    src={activeProject.mediaUrl} 
                    loop 
                    muted 
                    playsInline
                    key={activeProject.mediaUrl}
                  />
                  <div className="video-overlay" onClick={handleVideoControl}>
                    {!isPlaying && <div className="play-button">▶</div>}
                  </div>
                </>
              ) : (
                <img 
                  src={activeProject.mediaUrl} 
                  alt={activeProject.title}
                  key={activeProject.mediaUrl}
                />
              )}
            </div>
            
            <div className="project-info-overlay">
              <h2>{activeProject.title}</h2>
              <p>{activeProject.description}</p>
              <div className="project-links">
                {activeProject.detailsLink && activeProject.detailsLink !== '#' && (
                   <a href={activeProject.detailsLink} target="_blank" rel="noopener noreferrer">
                      🔗 View Details
                   </a>
                )}
                {activeProject.githubLink && activeProject.githubLink !== '#' && (
                  <a href={activeProject.githubLink} target="_blank" rel="noopener noreferrer">
                    💻 GitHub Repository
                  </a>
                )}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

export default ProjectsPage;